### ISSUE TITLE
Library needs documentation + examples

### ISSUE THREAD

**Issue by cmazakas** [cycfi/json#7]
I'll probably be volunteering on this front but wanted to simply raise awareness that what seems to be lacking is docs and examples.

**Comment by djowel** [comment]
Hi @LeonineKing1199, Yeah, so many things need to be documented.  Tell me what you have in mind you want to volunteer and how I can help.

**Comment by cmazakas** [comment]
We can improve the README to include a list of deps (the required versions of Boost and CMake).

Most READMEs also include a short little example to really pull users in so we need something flashy there too. Something that really shows off the power of the lib and why one would use it.

The API might actually be sufficiently small that we don't need anything more than the README.

Otherwise, we could just look into other doc generation tools and github pages.

As a potential user, all I really need to know is: what deps do I need, can I use it from CMake and how does parsing into a structure look like?

Let me know if this aligns with your vision. I don't have any strong opinions on layour or user experience. I just wanna help create the content.

**Comment by djowel** [comment]
That would be a good start. The lib includes some tests, actually, which can be used as examples. Feel free to do what you think. We can always improve later. I can add my ideas later as well. Yes, I think the readme is sufficient.
